// Minimal — generated by @web-kits/audio (do not edit)
// patch: Minimal
import type { SoundDefinition } from "@web-kits/audio"

export const click: SoundDefinition = {
  source: { type: "sine", frequency: 800 },
  envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
  gain: 0.17,
}
export const toggleOn: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 880 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      gain: 0.13,
    },
    {
      source: { type: "sine", frequency: 1320 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      delay: 0.03,
      gain: 0.12,
    },
  ],
}
export const toggleOff: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 1320 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      gain: 0.13,
    },
    {
      source: { type: "sine", frequency: 880 },
      envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.006 },
      delay: 0.03,
      gain: 0.12,
    },
  ],
}
export const copy: SoundDefinition = {
  layers: [
    {
      source: { type: "sine", frequency: 1000 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      gain: 0.13,
    },
    {
      source: { type: "sine", frequency: 1200 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      delay: 0.035,
      gain: 0.12,
    },
  ],
}
